spring:
  datasource:
    #    url: jdbc:mysql://localhost/oilpro?characterEncoding=utf-8&useSSL=false
    url: jdbc:sqlite:/Users/louis/Workspace/Code/Work/原型V1.0/preCast/src/main/resources/db/oilproject.db
    username: root
    password: root
    platform: sqlite
    # oracle.jdbc.driver.OracleDriver
    # driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.sqlite.JDBC
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    # type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #validationQuery: select 'x'
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的 小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  thymeleaf:
    prefix: classpath:/templates/
#  mvc:
#    static-path-pattern: /static/main/**


# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
  root: INFO
#  org.springframework: DEBUG
#  path: E://logs
